name: movie_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.1.2
  fast_immutable_collections: ^10.2.4
  cached_network_image: ^3.4.1
  state_notifier: ^1.0.0
  flutter_state_notifier: ^1.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
